server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
